env:
  browser: true
  node: true
  es6: true

extends:
  - airbnb

parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures: 
    jsx: true
plugins:
  - react
  - babel
rules: {
  react/prop-types: 0,
  jsx-a11y/label-has-associated-control: 0,
  import/extensions: 0
}
